<?php

namespace Database\Seeders;

use App\Models\CouponModel;
use Illuminate\Database\Seeder;

class CouponDemoSeeder extends Seeder
{
    public function run(): void
    {
        $coupons = [

            // ── Percentage Discounts ──────────────────────────────────────────

            [
                'coupon_name'         => 'Welcome 10% Off',
                'coupon_code'         => 'WELCOME10',
                'description'         => 'Get 10% off on your first order. Perfect for new customers! Max discount ₹200.',
                'discount_type'       => 'percentage',
                'discount_value'      => 10.00,
                'min_order_amount'    => 500.00,
                'max_discount_amount' => 200.00,
                'start_date'          => '2026-01-01',
                'expiry_date'         => '2026-12-31',
                'usage_limit'         => null,
                'used_count'          => 142,
                'per_user_limit'      => 1,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Summer Sale 25% Off',
                'coupon_code'         => 'SUMMER25',
                'description'         => 'Enjoy 25% off this summer on orders above ₹999. Max savings of ₹500.',
                'discount_type'       => 'percentage',
                'discount_value'      => 25.00,
                'min_order_amount'    => 999.00,
                'max_discount_amount' => 500.00,
                'start_date'          => '2026-06-01',
                'expiry_date'         => '2026-08-31',
                'usage_limit'         => 500,
                'used_count'          => 87,
                'per_user_limit'      => 2,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Electronics 15% Off',
                'coupon_code'         => 'ELEC15',
                'description'         => 'Save 15% on all electronics. Valid on orders above ₹5,000. Max discount ₹1,500.',
                'discount_type'       => 'percentage',
                'discount_value'      => 15.00,
                'min_order_amount'    => 5000.00,
                'max_discount_amount' => 1500.00,
                'start_date'          => '2026-06-01',
                'expiry_date'         => '2026-09-30',
                'usage_limit'         => 200,
                'used_count'          => 34,
                'per_user_limit'      => 1,
                'applicable_to'       => 'category',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Fashion 30% Off',
                'coupon_code'         => 'FASHION30',
                'description'         => 'Refresh your wardrobe — 30% off on fashion and clothing. Min cart ₹1,500, max ₹800 savings.',
                'discount_type'       => 'percentage',
                'discount_value'      => 30.00,
                'min_order_amount'    => 1500.00,
                'max_discount_amount' => 800.00,
                'start_date'          => '2026-06-15',
                'expiry_date'         => '2026-07-31',
                'usage_limit'         => 300,
                'used_count'          => 61,
                'per_user_limit'      => 2,
                'applicable_to'       => 'category',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'New App 20% Off',
                'coupon_code'         => 'NEWAPP20',
                'description'         => 'Download our app and get 20% off your first in-app order. One-time use only.',
                'discount_type'       => 'percentage',
                'discount_value'      => 20.00,
                'min_order_amount'    => 299.00,
                'max_discount_amount' => 300.00,
                'start_date'          => '2026-01-01',
                'expiry_date'         => '2026-12-31',
                'usage_limit'         => null,
                'used_count'          => 519,
                'per_user_limit'      => 1,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],

            // ── Fixed Cart Discounts ──────────────────────────────────────────

            [
                'coupon_name'         => 'Save ₹200',
                'coupon_code'         => 'SAVE200',
                'description'         => 'Flat ₹200 off on any order above ₹1,000. No product restrictions.',
                'discount_type'       => 'fixed_cart',
                'discount_value'      => 200.00,
                'min_order_amount'    => 1000.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-06-01',
                'expiry_date'         => '2026-09-30',
                'usage_limit'         => null,
                'used_count'          => 203,
                'per_user_limit'      => 3,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Flat ₹500 Off',
                'coupon_code'         => 'FLAT500',
                'description'         => 'Get ₹500 straight off on orders above ₹2,500. Limited period offer.',
                'discount_type'       => 'fixed_cart',
                'discount_value'      => 500.00,
                'min_order_amount'    => 2500.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-06-27',
                'expiry_date'         => '2026-07-31',
                'usage_limit'         => 150,
                'used_count'          => 12,
                'per_user_limit'      => 1,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Loyalty Reward ₹100',
                'coupon_code'         => 'LOYALTY100',
                'description'         => 'A thank-you coupon for our loyal customers. ₹100 off on any order, no minimum required.',
                'discount_type'       => 'fixed_cart',
                'discount_value'      => 100.00,
                'min_order_amount'    => 0.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-01-01',
                'expiry_date'         => '2026-12-31',
                'usage_limit'         => null,
                'used_count'          => 88,
                'per_user_limit'      => 5,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Flat ₹1000 Off Electronics',
                'coupon_code'         => 'TECH1000',
                'description'         => 'Big savings — ₹1,000 off on electronics orders above ₹10,000.',
                'discount_type'       => 'fixed_cart',
                'discount_value'      => 1000.00,
                'min_order_amount'    => 10000.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-06-27',
                'expiry_date'         => '2026-09-30',
                'usage_limit'         => 100,
                'used_count'          => 8,
                'per_user_limit'      => 1,
                'applicable_to'       => 'product',
                'status'              => 1,
            ],

            // ── Free Shipping ─────────────────────────────────────────────────

            [
                'coupon_name'         => 'Free Shipping',
                'coupon_code'         => 'FREESHIP',
                'description'         => 'Get free shipping on orders above ₹499. Valid across all categories.',
                'discount_type'       => 'free_shipping',
                'discount_value'      => 0.00,
                'min_order_amount'    => 499.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-01-01',
                'expiry_date'         => '2026-12-31',
                'usage_limit'         => null,
                'used_count'          => 1024,
                'per_user_limit'      => null,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Free Shipping All Orders',
                'coupon_code'         => 'SHIPFREE',
                'description'         => 'Free shipping with no minimum order value. Limited-time offer for all members.',
                'discount_type'       => 'free_shipping',
                'discount_value'      => 0.00,
                'min_order_amount'    => 0.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-06-27',
                'expiry_date'         => '2026-07-07',
                'usage_limit'         => 500,
                'used_count'          => 73,
                'per_user_limit'      => null,
                'applicable_to'       => 'all',
                'status'              => 1,
            ],

            // ── Buy X Get Y ───────────────────────────────────────────────────

            [
                'coupon_name'         => 'Buy 2 Get 1 Free',
                'coupon_code'         => 'BUY2GET1',
                'description'         => 'Add 3 items and the cheapest one is free. Applicable on fashion and home categories.',
                'discount_type'       => 'buy_x_get_y',
                'discount_value'      => 0.00,
                'min_order_amount'    => 0.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-06-01',
                'expiry_date'         => '2026-07-31',
                'usage_limit'         => 200,
                'used_count'          => 45,
                'per_user_limit'      => 2,
                'applicable_to'       => 'category',
                'status'              => 1,
            ],
            [
                'coupon_name'         => 'Buy 1 Get 1 50% Off',
                'coupon_code'         => 'B1G1HALF',
                'description'         => 'Buy one item and get the second at 50% off. Valid on clothing, shoes, and accessories.',
                'discount_type'       => 'buy_x_get_y',
                'discount_value'      => 50.00,
                'min_order_amount'    => 0.00,
                'max_discount_amount' => null,
                'start_date'          => '2026-06-27',
                'expiry_date'         => '2026-08-15',
                'usage_limit'         => 300,
                'used_count'          => 19,
                'per_user_limit'      => 3,
                'applicable_to'       => 'category',
                'status'              => 1,
            ],

            // ── Expired Coupons (for historical/demo purposes) ────────────────

            [
                'coupon_name'         => 'Diwali 40% Off',
                'coupon_code'         => 'DIWALI40',
                'description'         => 'Celebrate Diwali with 40% off sitewide. Max discount ₹1,000.',
                'discount_type'       => 'percentage',
                'discount_value'      => 40.00,
                'min_order_amount'    => 1000.00,
                'max_discount_amount' => 1000.00,
                'start_date'          => '2025-10-20',
                'expiry_date'         => '2025-11-05',
                'usage_limit'         => 1000,
                'used_count'          => 978,
                'per_user_limit'      => 2,
                'applicable_to'       => 'all',
                'status'              => 0,
            ],
            [
                'coupon_name'         => 'Republic Day Sale 26% Off',
                'coupon_code'         => 'REPUBLIC26',
                'description'         => 'Happy Republic Day! Enjoy 26% off on all products. Valid 26th January only.',
                'discount_type'       => 'percentage',
                'discount_value'      => 26.00,
                'min_order_amount'    => 500.00,
                'max_discount_amount' => 600.00,
                'start_date'          => '2026-01-26',
                'expiry_date'         => '2026-01-26',
                'usage_limit'         => 2000,
                'used_count'          => 1843,
                'per_user_limit'      => 1,
                'applicable_to'       => 'all',
                'status'              => 0,
            ],
            [
                'coupon_name'         => 'Holi 20% Off',
                'coupon_code'         => 'HOLI20',
                'description'         => 'Play with colours and save 20% on fashion and beauty this Holi.',
                'discount_type'       => 'percentage',
                'discount_value'      => 20.00,
                'min_order_amount'    => 799.00,
                'max_discount_amount' => 400.00,
                'start_date'          => '2026-03-13',
                'expiry_date'         => '2026-03-15',
                'usage_limit'         => 500,
                'used_count'          => 492,
                'per_user_limit'      => 1,
                'applicable_to'       => 'all',
                'status'              => 0,
            ],
        ];

        foreach ($coupons as $coupon) {
            CouponModel::updateOrCreate(
                ['coupon_code' => $coupon['coupon_code']],
                $coupon
            );
        }

        $this->command->info('Coupons seeded: ' . count($coupons));
    }
}
