<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\ProductGalleryImage;
use App\Models\ProductModel;
use App\Models\SubCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductDemoSeeder extends Seeder
{
    public function run(): void
    {
        // Helper to resolve IDs
        $cat = fn(string $slug) => Category::where('category_slug', $slug)->value('id');
        $sub = fn(string $slug) => SubCategory::where('subcategory_slug', $slug)->value('id');
        $brand = fn(string $slug) => Brand::where('brand_slug', $slug)->value('id');

        $products = [
            // ── Electronics / Smartphones ──────────────────────────────
            [
                'product_name'        => 'Apple iPhone 15 Pro (256GB, Natural Titanium)',
                'product_slug'        => 'apple-iphone-15-pro-256gb-natural-titanium',
                'short_description'   => 'The most advanced iPhone ever with A17 Pro chip, 48MP main camera and USB-C.',
                'description'         => '<p>Experience the power of the A17 Pro chip with a 6-core GPU. The 48MP Main camera with second-generation sensor-shift OIS delivers stunning detail. USB 3 speeds for fast data transfer. Titanium design — lighter and stronger.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 1 Year Apple India Warranty. <strong>In the box:</strong> iPhone, USB-C Cable, Documentation.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('smartphones'),
                'brand_id'            => $brand('apple'),
                'original_price'      => 134900,
                'selling_price'       => 119999,
                'cost_price'          => 95000,
                'discount'            => 11.05,
                'sku'                 => 'APL-IP15P-256-NT',
                'qty'                 => 50,
                'low_stock_alert'     => 5,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_iphone_15.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Apple iPhone 15 Pro 256GB Online - SelfBuy',
                'meta_description'    => 'Buy Apple iPhone 15 Pro 256GB Natural Titanium at the best price. A17 Pro chip, 48MP camera, USB-C.',
                'gallery'             => ['prod_iphone_15_g1.jpg'],
            ],
            [
                'product_name'        => 'Samsung Galaxy S24 Ultra (12GB/256GB, Titanium Black)',
                'product_slug'        => 'samsung-galaxy-s24-ultra-12gb-256gb-titanium-black',
                'short_description'   => 'Galaxy AI meets the Galaxy S series — the ultimate pro smartphone with built-in S Pen.',
                'description'         => '<p>200MP ProVisual Engine camera, Snapdragon 8 Gen 3, 5000 mAh battery with 45W fast charging. Built-in S Pen for next-level productivity.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 1 Year Samsung India Warranty.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('smartphones'),
                'brand_id'            => $brand('samsung'),
                'original_price'      => 129999,
                'selling_price'       => 114999,
                'cost_price'          => 90000,
                'discount'            => 11.54,
                'sku'                 => 'SAM-S24U-12-256-TB',
                'qty'                 => 40,
                'low_stock_alert'     => 5,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_samsung_s24.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Samsung Galaxy S24 Ultra 12GB 256GB Online',
                'meta_description'    => 'Buy Samsung Galaxy S24 Ultra at best price. 200MP camera, S Pen, Snapdragon 8 Gen 3.',
                'gallery'             => ['prod_samsung_s24_g1.jpg'],
            ],

            // ── Electronics / Laptops ─────────────────────────────────
            [
                'product_name'        => 'Apple MacBook Pro 14" M3 Pro (18GB/512GB, Space Black)',
                'product_slug'        => 'apple-macbook-pro-14-m3-pro-18gb-512gb-space-black',
                'short_description'   => 'Built for pros. M3 Pro chip with 12-core CPU and 18-core GPU, stunning Liquid Retina XDR display.',
                'description'         => '<p>The MacBook Pro 14-inch with M3 Pro delivers extraordinary performance and battery life. Liquid Retina XDR display with 120Hz ProMotion. Up to 18 hours of battery life.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 1 Year Apple India Limited Warranty.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('laptops'),
                'brand_id'            => $brand('apple'),
                'original_price'      => 199900,
                'selling_price'       => 189900,
                'cost_price'          => 160000,
                'discount'            => 5.00,
                'sku'                 => 'APL-MBP14-M3P-18-512',
                'qty'                 => 20,
                'low_stock_alert'     => 3,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_macbook_pro.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 0,
                'meta_title'          => 'Buy Apple MacBook Pro 14" M3 Pro Online - SelfBuy',
                'meta_description'    => 'Apple MacBook Pro 14 M3 Pro 18GB 512GB Space Black. Best performance laptop for professionals.',
                'gallery'             => ['prod_macbook_pro_g1.jpg'],
            ],
            [
                'product_name'        => 'Dell XPS 15 (Intel i7-13700H, 16GB/512GB, RTX 4060)',
                'product_slug'        => 'dell-xps-15-i7-13700h-16gb-512gb-rtx4060',
                'short_description'   => 'Premium 15.6" OLED laptop with 13th Gen Intel Core i7 and NVIDIA RTX 4060 graphics.',
                'description'         => '<p>The Dell XPS 15 features a stunning 15.6" 3.5K OLED display, 13th Gen Intel Core i7-13700H, 16GB DDR5 RAM, 512GB NVMe SSD, and NVIDIA GeForce RTX 4060 8GB. Perfect for creative professionals.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 1 Year Dell On-Site Warranty.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('laptops'),
                'brand_id'            => $brand('dell'),
                'original_price'      => 169990,
                'selling_price'       => 149990,
                'cost_price'          => 120000,
                'discount'            => 11.77,
                'sku'                 => 'DELL-XPS15-I7-16-512',
                'qty'                 => 15,
                'low_stock_alert'     => 3,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_dell_laptop.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Dell XPS 15 i7 16GB 512GB Online - SelfBuy',
                'meta_description'    => 'Dell XPS 15 with 13th Gen i7, RTX 4060, 3.5K OLED display. Best laptop for creative work.',
                'gallery'             => ['prod_dell_laptop_g1.jpg'],
            ],

            // ── Electronics / Headphones ──────────────────────────────
            [
                'product_name'        => 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
                'product_slug'        => 'sony-wh-1000xm5-wireless-noise-cancelling-headphones',
                'short_description'   => 'Industry-leading noise cancellation with 30-hour battery and crystal-clear hands-free calling.',
                'description'         => '<p>Sony WH-1000XM5 features the new V1 processor for best-in-class noise cancellation. Multipoint connection lets you switch between two Bluetooth devices. 30-hour battery life.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 1 Year Sony India Warranty.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('headphones'),
                'brand_id'            => $brand('sony'),
                'original_price'      => 29990,
                'selling_price'       => 22999,
                'cost_price'          => 16000,
                'discount'            => 23.31,
                'sku'                 => 'SNY-WH1000XM5-BLK',
                'qty'                 => 60,
                'low_stock_alert'     => 10,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_sony_headphones.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Sony WH-1000XM5 Headphones Online - SelfBuy',
                'meta_description'    => 'Sony WH-1000XM5 best noise cancelling wireless headphones with 30hr battery. Buy online at best price.',
                'gallery'             => ['prod_sony_headphones_g1.jpg'],
            ],

            // ── Electronics / Smart TVs ───────────────────────────────
            [
                'product_name'        => 'Samsung 55" QLED 4K Smart TV (QN90C, 2024)',
                'product_slug'        => 'samsung-55-qled-4k-smart-tv-qn90c-2024',
                'short_description'   => 'Neo QLED 4K with Quantum Mini LEDs, 144Hz gaming display, and Neural Quantum Processor 4K.',
                'description'         => '<p>Samsung 55" Neo QLED 4K QN90C delivers brilliant brightness and precision dimming using Quantum Mini LEDs. 144Hz refresh rate for smooth gaming. Tizen OS with built-in streaming apps.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 1 Year Samsung India Warranty + 1 Year Panel Warranty.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('smart-tvs'),
                'brand_id'            => $brand('samsung'),
                'original_price'      => 119990,
                'selling_price'       => 89999,
                'cost_price'          => 70000,
                'discount'            => 25.00,
                'sku'                 => 'SAM-QLED55-QN90C',
                'qty'                 => 25,
                'low_stock_alert'     => 3,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_samsung_tv.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 0,
                'meta_title'          => 'Buy Samsung 55" Neo QLED 4K Smart TV Online',
                'meta_description'    => 'Samsung 55 inch Neo QLED 4K QN90C Smart TV. 144Hz gaming, Quantum Mini LEDs. Best price online.',
                'gallery'             => ['prod_samsung_tv_g1.jpg'],
            ],

            // ── Electronics / Tablets ─────────────────────────────────
            [
                'product_name'        => 'Apple iPad Pro 12.9" M2 (256GB, Wi-Fi, Space Grey)',
                'product_slug'        => 'apple-ipad-pro-12-9-m2-256gb-wifi-space-grey',
                'short_description'   => 'The ultimate iPad experience with M2 chip, Liquid Retina XDR display, and Apple Pencil support.',
                'description'         => '<p>M2 chip with 8-core CPU, 10-core GPU. Stunning 12.9-inch Liquid Retina XDR display with ProMotion. Apple Pencil (2nd gen) and Magic Keyboard compatible. Wi-Fi 6E connectivity.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 1 Year Apple India Warranty.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('tablets'),
                'brand_id'            => $brand('apple'),
                'original_price'      => 112900,
                'selling_price'       => 99999,
                'cost_price'          => 80000,
                'discount'            => 11.43,
                'sku'                 => 'APL-IPDPRO12-M2-256',
                'qty'                 => 30,
                'low_stock_alert'     => 5,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_ipad_pro.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 0,
                'meta_title'          => 'Buy Apple iPad Pro 12.9" M2 256GB Online',
                'meta_description'    => 'Apple iPad Pro 12.9 M2 256GB WiFi Space Grey. Liquid Retina XDR, M2 chip, Apple Pencil support.',
                'gallery'             => ['prod_ipad_pro_g1.jpg'],
            ],

            // ── Electronics / Monitors ────────────────────────────────
            [
                'product_name'        => 'LG 27" 4K UHD IPS Monitor (27UK850-W, USB-C)',
                'product_slug'        => 'lg-27-4k-uhd-ips-monitor-27uk850-w-usbc',
                'short_description'   => '27-inch 4K IPS display with USB-C one-cable solution and HDR10 support.',
                'description'         => '<p>LG 27UK850-W 4K UHD IPS monitor delivers precise colours with DCI-P3 95% colour gamut. USB-C connectivity for power and data in one cable. HDR10 support, AMD FreeSync, and Height-adjustable stand.</p>',
                'additional_description' => '<p><strong>Warranty:</strong> 3 Years LG India On-Site Warranty.</p>',
                'category_id'         => $cat('electronics'),
                'sub_category_id'     => $sub('laptops'),
                'brand_id'            => $brand('lg'),
                'original_price'      => 49990,
                'selling_price'       => 37999,
                'cost_price'          => 28000,
                'discount'            => 24.00,
                'sku'                 => 'LG-27UK850W',
                'qty'                 => 35,
                'low_stock_alert'     => 5,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_lg_monitor.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 0,
                'meta_title'          => 'Buy LG 27" 4K UHD IPS Monitor Online - SelfBuy',
                'meta_description'    => 'LG 27 inch 4K UHD IPS monitor with USB-C, HDR10, AMD FreeSync. Best price online.',
                'gallery'             => ['prod_lg_monitor_g1.jpg'],
            ],

            // ── Fashion / Men's Wear ──────────────────────────────────
            [
                'product_name'        => "Men's Premium Puffer Jacket (Navy Blue, XL)",
                'product_slug'        => 'mens-premium-puffer-jacket-navy-blue-xl',
                'short_description'   => 'Lightweight insulated puffer jacket for men — warm, stylish, and packable.',
                'description'         => '<p>Stay warm in style with this premium puffer jacket. Features 100% polyester shell, synthetic insulation, zip pockets, and a packable design. Available in multiple colours and sizes.</p>',
                'additional_description' => '<p><strong>Care:</strong> Machine washable. <strong>Fit:</strong> Regular fit.</p>',
                'category_id'         => $cat('fashion-clothing'),
                'sub_category_id'     => $sub('mens-wear'),
                'brand_id'            => $brand('nike'),
                'original_price'      => 4999,
                'selling_price'       => 2999,
                'cost_price'          => 1500,
                'discount'            => 20.00,
                'sku'                 => 'NIKE-PUFFM-NVY-XL',
                'qty'                 => 100,
                'low_stock_alert'     => 15,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_mens_jacket.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 1,
                'meta_title'          => "Buy Men's Puffer Jacket Navy Blue Online - SelfBuy",
                'meta_description'    => "Shop men's premium puffer jacket. Lightweight, warm, and packable. Best price online.",
                'gallery'             => ['prod_mens_jacket_g1.jpg'],
            ],
            [
                'product_name'        => "Women's Floral Wrap Midi Dress (Multicolor, M)",
                'product_slug'        => 'womens-floral-wrap-midi-dress-multicolor-m',
                'short_description'   => 'Elegant floral wrap midi dress — perfect for brunch, parties, and casual outings.',
                'description'         => '<p>Beautiful floral print wrap midi dress with V-neckline and adjustable tie waist. 100% viscose for a flowy, comfortable feel. Available in sizes XS to XXL.</p>',
                'additional_description' => '<p><strong>Care:</strong> Hand wash cold. <strong>Fit:</strong> Wrap style, self-tie at waist.</p>',
                'category_id'         => $cat('fashion-clothing'),
                'sub_category_id'     => $sub('womens-wear'),
                'brand_id'            => $brand('puma'),
                'original_price'      => 2999,
                'selling_price'       => 1799,
                'cost_price'          => 900,
                'discount'            => 12.00,
                'sku'                 => 'PUMA-WDRS-FLR-M',
                'qty'                 => 80,
                'low_stock_alert'     => 10,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_womens_dress.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 1,
                'meta_title'          => "Buy Women's Floral Wrap Midi Dress Online",
                'meta_description'    => "Elegant women's floral wrap midi dress in multicolor. V-neckline, adjustable tie waist. Shop online.",
                'gallery'             => ['prod_womens_dress_g1.jpg'],
            ],
            [
                'product_name'        => 'Nike Air Max 270 Running Shoes (White/Black, UK 9)',
                'product_slug'        => 'nike-air-max-270-running-shoes-white-black-uk9',
                'short_description'   => "Nike's tallest Air unit yet in the heel delivers an ultra-soft ride for all-day use.",
                'description'         => '<p>The Nike Air Max 270 features a sleek upper with embroidered Swoosh and a Max Air 270 unit for visible cushioning. Foam midsole and rubber outsole for traction. Ideal for casual wear and light workouts.</p>',
                'additional_description' => '<p><strong>Upper:</strong> Mesh/synthetic. <strong>Sole:</strong> Rubber. <strong>Closure:</strong> Lace-up.</p>',
                'category_id'         => $cat('fashion-clothing'),
                'sub_category_id'     => $sub('shoes'),
                'brand_id'            => $brand('nike'),
                'original_price'      => 12995,
                'selling_price'       => 8999,
                'cost_price'          => 6000,
                'discount'            => 39.9,
                'sku'                 => 'NIKE-AM270-WB-UK9',
                'qty'                 => 70,
                'low_stock_alert'     => 10,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_nike_shoes.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Nike Air Max 270 Running Shoes Online',
                'meta_description'    => 'Nike Air Max 270 White/Black UK 9. Max Air cushioning, mesh upper. Buy running shoes online.',
                'gallery'             => ['prod_nike_shoes_g1.jpg'],
            ],
            [
                'product_name'        => 'Adidas Essentials 3-Stripes T-Shirt (Black, L)',
                'product_slug'        => 'adidas-essentials-3-stripes-tshirt-black-l',
                'short_description'   => 'Classic Adidas essentials tee with iconic 3-Stripes — simple, comfortable, and versatile.',
                'description'         => '<p>The Adidas Essentials 3-Stripes T-Shirt is made from 100% jersey cotton for everyday comfort. Regular fit with ribbed crew neckline. Available in Black, White, and Navy in sizes S to XXL.</p>',
                'additional_description' => '<p><strong>Material:</strong> 100% cotton jersey. <strong>Care:</strong> Machine washable.</p>',
                'category_id'         => $cat('fashion-clothing'),
                'sub_category_id'     => $sub('mens-wear'),
                'brand_id'            => $brand('adidas'),
                'original_price'      => 1499,
                'selling_price'       => 999,
                'cost_price'          => 450,
                'discount'            => 50.0,
                'sku'                 => 'ADI-ESS3S-BLK-L',
                'qty'                 => 200,
                'low_stock_alert'     => 20,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_adidas_tshirt.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 0,
                'meta_title'          => 'Buy Adidas Essentials 3-Stripes T-Shirt Online',
                'meta_description'    => 'Adidas Essentials 3-Stripes T-Shirt Black Large. 100% cotton, regular fit. Buy online at best price.',
                'gallery'             => ['prod_adidas_tshirt_g1.jpg'],
            ],

            // ── Home & Living ─────────────────────────────────────────
            [
                'product_name'        => '3-Seater Fabric Sofa (Grey, Modern Design)',
                'product_slug'        => '3-seater-fabric-sofa-grey-modern-design',
                'short_description'   => 'Premium 3-seater sofa in durable grey fabric with solid wood legs — built for comfort and style.',
                'description'         => '<p>This modern 3-seater sofa features high-density foam cushions, durable fabric upholstery, and solid wooden legs. Suitable for living rooms and lounges. Easy to assemble.</p>',
                'additional_description' => '<p><strong>Dimensions:</strong> 215 x 85 x 85 cm. <strong>Assembly:</strong> Required (tools included). <strong>Warranty:</strong> 1 Year.</p>',
                'category_id'         => $cat('home-living'),
                'sub_category_id'     => $sub('furniture'),
                'brand_id'            => null,
                'original_price'      => 29999,
                'selling_price'       => 19999,
                'cost_price'          => 13000,
                'discount'            => 10.0,
                'sku'                 => 'SOFA-3S-GRY-MOD',
                'qty'                 => 10,
                'low_stock_alert'     => 2,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_sofa.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 0,
                'meta_title'          => 'Buy 3-Seater Grey Fabric Sofa Online - SelfBuy',
                'meta_description'    => '3-seater modern grey fabric sofa with solid wood legs. High-density foam cushions. Buy online.',
                'gallery'             => ['prod_sofa_g1.jpg'],
            ],
            [
                'product_name'        => 'Philips LED Desk Lamp with USB Charging Port (White)',
                'product_slug'        => 'philips-led-desk-lamp-usb-charging-white',
                'short_description'   => 'Stylish LED desk lamp with adjustable brightness, 5 color modes, and built-in USB port.',
                'description'         => '<p>The Philips LED desk lamp offers 5 brightness levels and 5 color temperatures for the perfect ambience. Built-in USB charging port to keep your devices powered. Eye-care technology reduces flicker.</p>',
                'additional_description' => '<p><strong>Power:</strong> 10W LED (60W equivalent). <strong>Warranty:</strong> 2 Years Philips India.</p>',
                'category_id'         => $cat('home-living'),
                'sub_category_id'     => $sub('lighting'),
                'brand_id'            => $brand('philips'),
                'original_price'      => 3499,
                'selling_price'       => 1999,
                'cost_price'          => 1000,
                'discount'            => 15.00,
                'sku'                 => 'PHL-DESKL-USB-WHT',
                'qty'                 => 150,
                'low_stock_alert'     => 20,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_lamp.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Philips LED Desk Lamp with USB Port Online',
                'meta_description'    => 'Philips LED desk lamp, 5 brightness levels, 5 color modes, USB charging port. Eye care technology.',
                'gallery'             => ['prod_lamp_g1.jpg'],
            ],
            [
                'product_name'        => 'King Size Microfibre Bedding Set (6 Piece, White)',
                'product_slug'        => 'king-size-microfibre-bedding-set-6-piece-white',
                'short_description'   => 'Luxurious 6-piece king size microfibre bedding set — soft, breathable, and easy care.',
                'description'         => '<p>Complete your bedroom with this premium 6-piece microfibre bedding set: 1 duvet cover, 2 pillow shams, 1 fitted sheet, and 2 pillowcases. 1800 thread-count equivalent softness. Machine washable.</p>',
                'additional_description' => '<p><strong>Includes:</strong> 1 Duvet Cover, 2 Pillow Shams, 1 Fitted Sheet, 2 Pillowcases. <strong>Care:</strong> Machine wash cold, tumble dry low.</p>',
                'category_id'         => $cat('home-living'),
                'sub_category_id'     => $sub('bedding'),
                'brand_id'            => null,
                'original_price'      => 4999,
                'selling_price'       => 2799,
                'cost_price'          => 1500,
                'discount'            => 22.00,
                'sku'                 => 'BED-KNG-MF-6P-WHT',
                'qty'                 => 80,
                'low_stock_alert'     => 10,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_bedding_set.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 0,
                'meta_title'          => 'Buy King Size Microfibre Bedding Set 6 Piece Online',
                'meta_description'    => 'King size 6-piece microfibre bedding set in white. Soft, breathable, and machine washable.',
                'gallery'             => ['prod_bedding_set_g1.jpg'],
            ],

            // ── Sports ────────────────────────────────────────────────
            [
                'product_name'        => 'SS Ton Reserve Edition Cricket Bat (Short Handle)',
                'product_slug'        => 'ss-ton-reserve-edition-cricket-bat-short-handle',
                'short_description'   => 'Premium English willow cricket bat ideal for hard ball cricket — powerful and durable.',
                'description'         => '<p>SS Ton Reserve Edition cricket bat crafted from Grade 1 English Willow with a traditional spine and round edge. Short handle, balanced pick-up weight, and extra-thick edges for maximum power shots.</p>',
                'additional_description' => '<p><strong>Willow:</strong> Grade 1 English Willow. <strong>Handle:</strong> Short handle, round cane handle. <strong>Includes:</strong> Bat + Grip.</p>',
                'category_id'         => $cat('sports-outdoors'),
                'sub_category_id'     => $sub('cricket'),
                'brand_id'            => null,
                'original_price'      => 9999,
                'selling_price'       => 7499,
                'cost_price'          => 5000,
                'discount'            => 25.00,
                'sku'                 => 'SS-TON-RE-SH',
                'qty'                 => 30,
                'low_stock_alert'     => 5,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_cricket_bat.jpg',
                'status'              => 1,
                'is_featured'         => 1,
                'is_trending'         => 0,
                'meta_title'          => 'Buy SS Ton Reserve Edition Cricket Bat Online',
                'meta_description'    => 'SS Ton Reserve Edition Grade 1 English Willow cricket bat. Short handle. Buy online at best price.',
                'gallery'             => ['prod_cricket_bat_g1.jpg'],
            ],
            [
                'product_name'        => 'Nivia Storm Football (Size 5, Black/White)',
                'product_slug'        => 'nivia-storm-football-size-5-black-white',
                'short_description'   => 'Match-quality PU football for outdoor and futsal play — durable and true-flight.',
                'description'         => '<p>Nivia Storm football is made from high-quality synthetic PU material with machine stitching for consistent flight. Size 5 is the official match size. Suitable for grass, turf, and indoor courts.</p>',
                'additional_description' => '<p><strong>Size:</strong> 5 (Official Match Size). <strong>Material:</strong> Synthetic PU. <strong>Stitching:</strong> Machine stitched.</p>',
                'category_id'         => $cat('sports-outdoors'),
                'sub_category_id'     => $sub('football'),
                'brand_id'            => null,
                'original_price'      => 1299,
                'selling_price'       => 899,
                'cost_price'          => 500,
                'discount'            => 40.0,
                'sku'                 => 'NIVIA-STRM-FB-5-BW',
                'qty'                 => 100,
                'low_stock_alert'     => 15,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_football.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 0,
                'meta_title'          => 'Buy Nivia Storm Football Size 5 Online',
                'meta_description'    => 'Nivia Storm football size 5 in black and white. Match quality PU material. Buy online.',
                'gallery'             => ['prod_football_g1.jpg'],
            ],
            [
                'product_name'        => 'Boldfit 6mm Thick Non-Slip Yoga Mat (Purple)',
                'product_slug'        => 'boldfit-6mm-thick-non-slip-yoga-mat-purple',
                'short_description'   => 'Extra-thick 6mm eco-friendly yoga mat with carrying strap — perfect for yoga, pilates, and stretching.',
                'description'         => '<p>Boldfit yoga mat features 6mm thick foam for extra cushioning and joint protection. Non-slip texture on both sides for superior grip. Lightweight with a carrying strap for easy transport.</p>',
                'additional_description' => '<p><strong>Dimensions:</strong> 183 x 61 cm x 6mm. <strong>Material:</strong> NBR foam. <strong>Includes:</strong> Yoga mat + Carrying strap.</p>',
                'category_id'         => $cat('sports-outdoors'),
                'sub_category_id'     => $sub('yoga-fitness'),
                'brand_id'            => null,
                'original_price'      => 999,
                'selling_price'       => 599,
                'cost_price'          => 300,
                'discount'            => 40.0,
                'sku'                 => 'BOLD-YOGA6-PUR',
                'qty'                 => 200,
                'low_stock_alert'     => 25,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_yoga_mat.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Boldfit 6mm Yoga Mat Purple Online - SelfBuy',
                'meta_description'    => 'Boldfit 6mm non-slip yoga mat in purple. Extra cushioning, lightweight, with carrying strap.',
                'gallery'             => ['prod_yoga_mat_g1.jpg'],
            ],

            // ── Beauty ────────────────────────────────────────────────
            [
                'product_name'        => 'Himalaya Herbals Nourishing Skin Cream (400ml)',
                'product_slug'        => 'himalaya-herbals-nourishing-skin-cream-400ml',
                'short_description'   => 'Moisturises and nourishes dry skin with the goodness of winter cherry and aloe vera.',
                'description'         => '<p>Himalaya Herbals Nourishing Skin Cream is enriched with Winter Cherry (Ashwagandha) and Aloe Vera that provide natural moisturisation and keep skin soft and supple. Dermatologically tested, non-greasy formula.</p>',
                'additional_description' => '<p><strong>Key Ingredients:</strong> Winter Cherry (Ashwagandha), Aloe Vera. <strong>Skin type:</strong> All skin types. <strong>Usage:</strong> Apply daily after wash.</p>',
                'category_id'         => $cat('beauty-personal-care'),
                'sub_category_id'     => $sub('skincare'),
                'brand_id'            => null,
                'original_price'      => 375,
                'selling_price'       => 290,
                'cost_price'          => 150,
                'discount'            => 8.5,
                'sku'                 => 'HIM-NSC-400ML',
                'qty'                 => 300,
                'low_stock_alert'     => 30,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_face_cream.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 0,
                'meta_title'          => 'Buy Himalaya Nourishing Skin Cream 400ml Online',
                'meta_description'    => 'Himalaya Herbals Nourishing Skin Cream 400ml. Winter cherry, aloe vera. Non-greasy, dermatologically tested.',
                'gallery'             => ['prod_face_cream_g1.jpg'],
            ],
            [
                'product_name'        => 'Lakme Absolute Luxe Matte Lip Color (Wine & Dine)',
                'product_slug'        => 'lakme-absolute-luxe-matte-lip-color-wine-and-dine',
                'short_description'   => 'Long-lasting matte lipstick enriched with vitamin E — intense colour with comfortable wear.',
                'description'         => '<p>Lakme Absolute Luxe Matte Lip Color delivers intense, opaque matte colour that lasts up to 12 hours. Enriched with Vitamin E for a comfortable, non-drying formula. Shade: Wine & Dine — a deep berry-red.</p>',
                'additional_description' => '<p><strong>Shade:</strong> Wine & Dine. <strong>Finish:</strong> Matte. <strong>Key Benefit:</strong> Up to 12-hour wear, Vitamin E enriched.</p>',
                'category_id'         => $cat('beauty-personal-care'),
                'sub_category_id'     => $sub('makeup'),
                'brand_id'            => null,
                'original_price'      => 699,
                'selling_price'       => 519,
                'cost_price'          => 280,
                'discount'            => 18.0,
                'sku'                 => 'LAK-ABSLX-LIP-WAD',
                'qty'                 => 250,
                'low_stock_alert'     => 30,
                'stock_status'        => 'in_stock',
                'product_image'       => 'prod_lipstick.jpg',
                'status'              => 1,
                'is_featured'         => 0,
                'is_trending'         => 1,
                'meta_title'          => 'Buy Lakme Absolute Luxe Matte Lip Color Online',
                'meta_description'    => 'Lakme Absolute Luxe Matte Lip Color in Wine & Dine. 12-hour wear, Vitamin E, matte finish.',
                'gallery'             => ['prod_lipstick_g1.jpg'],
            ],
        ];

        foreach ($products as $data) {
            $gallery = $data['gallery'] ?? [];
            unset($data['gallery']);

            $product = ProductModel::updateOrCreate(
                ['product_slug' => $data['product_slug']],
                $data
            );

            // Add gallery images (skip if already exists)
            if ($product->wasRecentlyCreated || $product->galleryImages()->count() === 0) {
                $product->galleryImages()->delete();
                foreach ($gallery as $idx => $img) {
                    ProductGalleryImage::create([
                        'product_id'  => $product->id,
                        'image_path'  => $img,
                        'sort_order'  => $idx + 1,
                    ]);
                }
            }
        }

        $this->command->info('Products seeded: ' . count($products));
    }
}
